name: 'Deployment Tests'

on:
  push:
    branches:
      - main
      - develop

jobs:
  ############################# Deployment Tests for MCP modules #####################################################
  MCP-tests:
    runs-on: ubuntu-latest

    env:
      working-directory: ./tests/mcp/deployment
      GCP_PROJECT_ID: "mcpdeploytest-${GITHUB_SHA::8}-$(date +%H%M%S)"
      KUBE_CONFIG_PATH: ~/.kube/config

    defaults:
      run:
        shell: bash
        working-directory: ${{env.working-directory}}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      # Authenticate using workload identity federation
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{secrets.GCP_SA_EMAIL}}
          workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER}}
          token_format: 'access_token'
          access_token_lifetime: 1200s # 20 minutes

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Set constant variables
        id: vars
        run: echo "::set-output name=GCP_PROJECT_ID::${{ env.GCP_PROJECT_ID }}"

      # Create a project and enable billing and other services
      # Configure buckets to be used, constrained to europe-west2 to match organization policies.
      - name: Setup GCP
        run: |
          gcloud projects create ${{ steps.vars.outputs.GCP_PROJECT_ID }} --folder=${{secrets.GCP_FOLDER_ID}} --set-as-default
          gcloud components install beta --quiet
          gcloud beta billing projects link ${{ steps.vars.outputs.GCP_PROJECT_ID }} --billing-account=${{secrets.GCP_BILLING_ID}}
          gcloud services enable cloudresourcemanager.googleapis.com
          gcloud services enable cloudbuild.googleapis.com
          gcloud services enable container.googleapis.com
          gcloud services enable appengine.googleapis.com
          gcloud services enable appengineflex.googleapis.com
          gcloud services enable artifactregistry.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud config set compute/zone europe-west2-a
          gsutil mb -l europe-west2 gs://${{ steps.vars.outputs.GCP_PROJECT_ID }}_bucket
          gsutil mb -l europe-west2 gs://${{ steps.vars.outputs.GCP_PROJECT_ID }}_cloudbuild

      # Create a new service account to be used for deployment
      - name: Create New SA
        run: |
          gcloud iam service-accounts create ga-deploy --description="Deploy with github actions" --display-name="Service account deploys through github action"
          gcloud iam service-accounts keys create ./sa-key.json --iam-account ga-deploy@${{ steps.vars.outputs.GCP_PROJECT_ID }}.iam.gserviceaccount.com --no-user-output-enabled
          gcloud projects add-iam-policy-binding ${{ steps.vars.outputs.GCP_PROJECT_ID }} --member="serviceAccount:ga-deploy@${{ steps.vars.outputs.GCP_PROJECT_ID }}.iam.gserviceaccount.com" --role="roles/owner" --no-user-output-enabled
          gcloud projects add-iam-policy-binding ${{ steps.vars.outputs.GCP_PROJECT_ID }} --member="serviceAccount:ga-deploy@${{ steps.vars.outputs.GCP_PROJECT_ID }}.iam.gserviceaccount.com" --role="roles/artifactregistry.admin" --no-user-output-enabled
          gcloud auth activate-service-account --key-file=sa-key.json

      # Configure yaml files to contain relevant project info
      - name: Add project ID to GCP Files
        run: |
          cd GCP
          echo "name: ${{ steps.vars.outputs.GCP_PROJECT_ID }}_app_bucket" > project.yml
          sed -i "s/<project_id>/${{ steps.vars.outputs.GCP_PROJECT_ID }}/" gcp_ae.yml
          sed -i "s/<image_uri>/europe-west2-docker.pkg.dev\/${{ steps.vars.outputs.GCP_PROJECT_ID }}\/app-repo\/helloworld:latest/" gcp_ae.yml
          sed -i "s/<project_id>/${{ steps.vars.outputs.GCP_PROJECT_ID }}/" gcp_cloudrun.yml

      # Deploy app image to Artifact Repository
      - name: Build App
        run: |
          cd GCP/app/build/helloworld
          timeout 420 bash -c 'while ! gcloud artifacts repositories create app-repo --repository-format=docker --location=europe-west2 --description="Repository for storing app"; do echo "Retrying in 30s" && sleep 30; done'
          gcloud builds submit --tag europe-west2-docker.pkg.dev/${{ steps.vars.outputs.GCP_PROJECT_ID }}/app-repo/helloworld

      # Configure yaml files to contain relevant project info
      - name: Add image URI to GCP Files
        run: |
          cd GCP
          sed -i "s/<image_uri>/europe-west2-docker.pkg.dev\/${{ steps.vars.outputs.GCP_PROJECT_ID }}\/app-repo\/helloworld:latest/" gcp_ae.yml
          sed -i "s/<image_uri>/europe-west2-docker.pkg.dev\/${{ steps.vars.outputs.GCP_PROJECT_ID }}\/app-repo\/helloworld:latest/" gcp_cloudrun.yml

      # Setup main.tf and deploy gcp modules. Also plan destroy but don't apply due to app engine issues.
      - name: Deploy GCP modules
        run: |
          cd GCP/terraform
          sleep 5m
          sed -i "s/gcs-bucket-name/${{ steps.vars.outputs.GCP_PROJECT_ID }}_bucket/" main.tf
          sed -i "s/source-path/..\/..\/..\/..\/..\//" main.tf
          cat main.tf
          terraform init
          terraform plan -out="./plan.tfplan"
          terraform apply plan.tfplan
          terraform plan -destroy -out="./destroy.tfplan"

      # Install kubectl and create gke cluster
      - name: setup kubectl
        run: |
          gcloud components install kubectl
          gcloud container clusters create-auto mcpdeploytest-cluster --region=europe-west2
          gcloud container clusters get-credentials mcpdeploytest-cluster --region=europe-west2

      # Setup main.tf, deploy and destroy k8s
      - name: deploy k8s
        run: |
          cd k8s/terraform
          sed -i "s/gcs-bucket-name/${{ steps.vars.outputs.GCP_PROJECT_ID }}_bucket/" main.tf
          sed -i "s/source-path/..\/..\/..\/..\/..\//" main.tf
          cat main.tf
          terraform init
          terraform plan -out="./plan.tfplan"
          terraform apply plan.tfplan
          terraform plan -destroy -out="./destroy.tfplan"
          terraform apply destroy.tfplan

      - name: delete project
        if: ${{ always() }}
        run: |
          gcloud projects delete ${{ steps.vars.outputs.GCP_PROJECT_ID }}
      #          gcloud beta billing projects unlink ${{ steps.vars.outputs.GCP_PROJECT_ID }} #Unlinking billing doesn't seem to be necessary